# Generated by Django 5.2.6 on 2025-09-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('mname', models.CharField(max_length=100)),
                ('colour', models.CharField()),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
